# Generated by Django 4.1.5 on 2023-09-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.ImageField(default='', max_length=20, upload_to='')),
                ('Email', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
