# Generated by Django 4.1.5 on 2023-09-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RE', '0002_kk1_alter_kk_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='bd1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=80)),
                ('Age', models.IntegerField(default='')),
                ('City', models.CharField(max_length=150)),
            ],
        ),
    ]
